#!/usr/bin/env node
/**
 * The public API of each package, as a reviewable text file.
 *
 *   node tools/check-api.mjs            compare dist against api/*.api.md
 *   node tools/check-api.mjs --write    regenerate the reports
 *
 * The report is generated from the **built** `.d.ts`, not from the sources, for
 * the same reason the token tests read the generated CSS: what a consumer
 * installs is the artefact, and a report taken from the authoring format can
 * agree with the code while disagreeing with the package.
 *
 * What this buys is that removing an export, narrowing an input, or widening a
 * return type all show up as a diff in a file a person reads, rather than as a
 * consumer's build failing after a release. It is not a substitute for
 * versioning; it is what makes versioning a decision somebody makes on purpose.
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import ts from 'typescript';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const write = process.argv.includes('--write');

const packages = [
  { name: '@cordly/ui', entry: 'dist/ui/types/cordly-ui.d.ts', report: 'api/ui.api.md' },
  {
    name: '@cordly/widgets',
    entry: 'dist/widgets/types/cordly-widgets.d.ts',
    report: 'api/widgets.api.md',
  },
];

/**
 * Strip documentation and collapse whitespace.
 *
 * Comments are removed on purpose. A doc comment is worth writing and worth
 * reading in the source, but if it reached this report then rewording one would
 * look exactly like changing an API — and a report whose diff is usually noise
 * is a report nobody reads. What survives is the shape: names, types, inputs,
 * outputs, and Angular's own component declaration, which encodes the selector
 * and the content-projection slots.
 */
function normalise(text) {
  return text
    .replace(/\r\n/g, '\n')
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .replace(/^[ \t]*\/\/.*$/gm, '')
    .replace(/[ \t]+/g, ' ')
    .replace(/\n\s*\n+/g, '\n')
    .trim();
}

function reportFor(pkg) {
  const entry = join(root, pkg.entry);
  const program = ts.createProgram([entry], {
    target: ts.ScriptTarget.ES2022,
    module: ts.ModuleKind.ESNext,
    moduleResolution: ts.ModuleResolutionKind.Bundler,
    skipLibCheck: true,
    declaration: true,
  });
  const checker = program.getTypeChecker();
  const source = program.getSourceFile(entry);
  if (!source) throw new Error(`cannot read ${pkg.entry}. Run: npm run build`);

  const moduleSymbol = checker.getSymbolAtLocation(source);
  if (!moduleSymbol) throw new Error(`${pkg.entry} exports nothing`);

  const lines = [
    `# ${pkg.name} public API`,
    '',
    '<!-- GENERATED by tools/check-api.mjs. Regenerate: npm run api:extract -->',
    '',
    'Every entry below is part of the package contract. Removing or narrowing one',
    'is a breaking change; see VERSIONING.md.',
    '',
  ];

  const exports = checker
    .getExportsOfModule(moduleSymbol)
    .slice()
    .sort((a, b) => a.getName().localeCompare(b.getName()));

  for (const symbol of exports) {
    // The entry point is a barrel of re-exports, so the first declaration of an
    // exported symbol is the `export { X } from './y'` specifier — a name and
    // nothing else. Resolving the alias reaches the real declaration in the
    // emitted `.d.ts`, which is what makes this report worth reading: an input
    // that changes type, or an output that is removed, shows up in the diff.
    const resolved =
      (symbol.flags & ts.SymbolFlags.Alias) !== 0 ? checker.getAliasedSymbol(symbol) : symbol;

    const declarations = resolved.getDeclarations() ?? [];
    const declaration = declarations[0];
    if (!declaration) continue;

    const kind = ts.isClassDeclaration(declaration)
      ? 'class'
      : ts.isInterfaceDeclaration(declaration)
        ? 'interface'
        : ts.isTypeAliasDeclaration(declaration)
          ? 'type'
          : ts.isFunctionDeclaration(declaration)
            ? 'function'
            : 'value';

    lines.push(`## ${kind} ${symbol.getName()}`);
    lines.push('');
    lines.push('```ts');
    lines.push(normalise(declaration.getText()));
    lines.push('```');
    lines.push('');
  }

  return `${lines.join('\n').trimEnd()}\n`;
}

let failed = false;

for (const pkg of packages) {
  const report = reportFor(pkg);
  const target = join(root, pkg.report);

  if (write) {
    mkdirSync(dirname(target), { recursive: true });
    writeFileSync(target, report, 'utf8');
    process.stdout.write(`api: wrote ${pkg.report}\n`);
    continue;
  }

  let committed;
  try {
    committed = readFileSync(target, 'utf8').replace(/\r\n/g, '\n');
  } catch {
    process.stderr.write(`api: ${pkg.report} is missing. Run: npm run api:extract\n`);
    failed = true;
    continue;
  }

  if (committed !== report) {
    process.stderr.write(
      `api: ${pkg.name} exports differ from ${pkg.report}. Review the change, decide whether it is breaking, then run: npm run api:extract\n`,
    );
    failed = true;
    continue;
  }

  const count = report.split('\n').filter((line) => line.startsWith('## ')).length;
  process.stdout.write(`api: ${pkg.name} matches its report (${count} exports)\n`);
}

process.exit(failed ? 1 : 0);
